### ISSUE TITLE
Dropping support for DB backends other than PostgreSQL

### ISSUE THREAD

**Issue by eoyilmaz** [eoyilmaz/stalker#29]
I'm planing to drop DB backend support other than PostgreSQL.

The main reason for that is to greatly optimize the code for only one db backend in mind and stop struggling with keeping the code universal.

There are great data types/instructions/constrains unique to PostgreSQL, but I can't use them just because other backends doesn't support them.

So, before doing that I wanted to here if anyone have any idea about why I shouldn't do that.

**Comment by fredrikaverpil** [comment]
We are going to run Stalker on PostgreSQL so I'm all for it.

**Comment by eoyilmaz** [comment]
Ok, with my next push this will be done, so I'm closing this one.
