### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by fredrikaverpil** [eoyilmaz/stalker#34]
I'm currently developing in Python 3 and will be using stalker. I've been performing a few queries and so far it's working great.

Are you aware of any issues I might stumble upon or should stalker be "Python 3 safe"?

**Comment by eoyilmaz** [comment]
2 years ago I've worked on the 3.x compatibility and done everything that makes Stalker Python 3.x compatible.

So there should be no major problems, but I haven't run the tests against Python 3.x quite some time.

**Comment by fredrikaverpil** [comment]
That is excellent!! 🎉🍻 

I'll close this issue then and create a new issue if anything pops up.
