### ISSUE TITLE
Upgrade instructions missing from documentation

### ISSUE THREAD

**Issue by fredrikaverpil** [eoyilmaz/stalker#35]
I think it would be very useful if we added upgrade instructions to [the documentation](https://pythonhosted.org/stalker/), since you need to use alembic to fix your db prior to `pip install -U stalker`.

**Comment by fredrikaverpil** [comment]
Actually, it would be even more desirable if stalker could update the db (with alembic) automagically whenever needed.

**Comment by eoyilmaz** [comment]
I prefer somebody else is doing the update instead of Stalker. Yes we should update the documentation in this regard.

**Comment by eoyilmaz** [comment]
Ok, I've finally been able to update the [documentation](https://pythonhosted.org/stalker/), I've also included the [Alembic upgrade instructions ](https://pythonhosted.org/stalker/upgrade_db.html)

**Comment by fredrikaverpil** [comment]
Great, thanks :)
