### ISSUE TITLE
date_updated not being set automatically on db.DBSession.commit()

### ISSUE THREAD

**Issue by fredrikaverpil** [eoyilmaz/stalker#39]
I'm noticing that when I update something in the database, the `date_updated` attribute isn't updated automatically.

When I e.g. change a user's email address, how can I make sure that the `User.date_updated` gets updated?

**Comment by eoyilmaz** [comment]
Update it by hand, there is no easy way until we implement an "auto
logger", which will create a log entry for every change between commits
showing both the old and new value and who has done the change and when.

**Comment by fredrikaverpil** [comment]
Ok, thanks.
