### ISSUE TITLE
Where to store information about environment?

### ISSUE THREAD

**Issue by fredrikaverpil** [eoyilmaz/stalker#40]
Hi,

I've previously stored environment variables (which is used for software version control) in the `generic_text` attribute of the `Version` SOM.

I now intend to change this approach as multiple `Version`s store the same environment and I actually think this might make up 50% of all data in our Stalker db by now.

So instead I'd like to be able to store each unique environment into something. Then I'd just save down a reference to this environment on the `Version`.

Which SOM would you suggest I use to store these environments?
It's plain text and I'm going to process it into a Python dictionary, JSON and YAML.

I first thought maybe I could use the `Note` SOM and set its `type` attribute using the `Type` SOM (for example of type "Environment"). I would then attach this `Note` to each `Version` object. Do you think this is a good idea or do you have any other suggestions?

**Comment by eoyilmaz** [comment]
I think ``Note`` with a custom ``Type`` is a good approach. But to differentiate the **normal** ``Note``s from your data storage ones, (assuming that you are using ``Version.notes`` for storing regular notes) you need to be constantly filtering these out, i.e. in your GUI.

Alternatively, you can use ``Version.generic_data`` to attach other ``SimpleEntities`` where you can add your custom text in ``SimpleEntity.description`` and you can again set a custom ``Type`` for them, thus you don't need to filter the ``Note``s as in the previous approach.

**Comment by fredrikaverpil** [comment]
That's a great suggestion, thanks!

**Comment by eoyilmaz** [comment]
can we close this issue

**Comment by fredrikaverpil** [comment]
Oh, yes. Absolutely!
