### ISSUE TITLE
Hi i have problem when using stalker in maya 

### ISSUE THREAD

**Issue by tws0002** [eoyilmaz/stalker#42]
1st big Thanks for sharing all this awesome stuff with the vex community!!! Thank you.

hi do you provide a documentation for anima setup ?
because i have problem when using anima and stalker in maya python!!

here is the error

import stalker
Error: line 1: ImportError: file line 1: No module named stalker
import anima
Error: line 1: ImportError: file line 1: No module named anima
------------------------------------------------------------------------
http://vfx.animaistanbul.com/stalker_home/
can you share how to setup anima, stalker and stalker_pyramid for a small scale studio pipeline?
im so confuse when using anima!! not sure where to start!! please help

**Comment by fredrikaverpil** [comment]
That error indicates that the Python environment don't know where the stalker module is located.

You can tell Maya to look for it somewhere by executing something like this prior to attempting to importing stalker:

```python
import site
site.addsitedir('C:/python_modules/')
```

Then you make sure you have the "stalker" folder/module in `C:/python_modules`.

**Comment by eoyilmaz** [comment]
Ooh I didn't recognize that I skipped this issue. I've updated the documentation of [anima](https://github.com/eoyilmaz/anima) some time ago, and explained how to install it.
