### ISSUE TITLE
User.password = <str> vs <unicode>

### ISSUE THREAD

**Issue by fredrikaverpil** [eoyilmaz/stalker#43]
I've created a UI where the user can enter a new password. With Python 2.7, the new password is read in from the UI as `unicode` while in Python 3.5, the password is read in as `str`. It seems that when setting the password in 2.7/`unicode`, all is fine. But when entering the password in 3.6/`str`, this is not handled properly and the password is essentially b0rked.

The docs just say "password (str)", but in this case str is two very different things (as they differ in Python 2 vs 3).

### Python 2.7 behavior

```python
>>> print(new_password.__class__.__name__)
unicode
>>> some_user.password = new_password
```

Database entry for the password: `aGVsbG8=` (correct)

### Python 3.5 behavior

```python
>>> print(new_password.__class__.__name__)
str
>>> some_user.password = new_password
```

Database entry for the password: `\x595564...` (incorrect)

**Comment by fredrikaverpil** [comment]
This also causes the `User.check_password(RAW_PASSWORD)` to always return `False`.

**Comment by fredrikaverpil** [comment]
I updated the code above to fix a few errors.

**Comment by jasperges** [comment]
The other day I also encountered this. I think you can change the `raw_password_mangled_str` assignments to `raw_password_mangled_str = raw_password_bytes.encode('utf-8')` which will work in Python 2.7 and 3.x.

Another thing I found out is that `sqlalchemy` uses `pickle` to dump things to the database. On Python 3.5 the highest `pickle` protocol is 4 while it is 2 on Python 2.7. These protocol versions are also the default ones used. So when you add things with Python 3.5 (pickle protocol 4) to the database, you can't load them with Python 2.7 (pickle protocol 2). I don't know if this is in any way related, but I thought I'd mention it. Because it seems you can't mix Python 2.7 and Python 3.5 in the same pipeline with `stalker`. Which is a shame, but hopefully we can find a solution for this.

**Comment by eoyilmaz** [comment]
I was not running the tests under Python 3.x for a while, so let me look in to the issue and restart taking Python 3.x development seriously.

I'll probably implement your code Fredrik you can create a pull request for that.

P.S.: I didn't know that somebody other than me and Fredrik was also using Stalker actively, so welcome Jasper.

**Comment by fredrikaverpil** [comment]
> I'll probably implement your code Fredrik you can create a pull request for that.

Ok, will do. I'll also take a stab at what's happening when you are trying to set a password from Python 3.5 since that doesn't seem to work without garbling the password into some binary ascii-like string. Without having looked at the code, I'm guessing it has to do with how 2.7 and 3.5 handles `str` differently.

> Because it seems you can't mix Python 2.7 and Python 3.5 in the same pipeline with stalker. Which is a shame, but hopefully we can find a solution for this.

@jasperges This is news to me. I've been using Python 2.7 and 3.5 with Stalker in development (not in production yet) which is operating on the very same database without noticing any issues (except from this I'm reporting here). Are you sure this is really a real-world problem with Stalker?
I was planning on deploying Python 3 into our pipeline within the next month or so and I'm very serious about getting this to happen and work flawlessly.

**Comment by fredrikaverpil** [comment]
@jasperges Am I correct to believe the sqlalchemy/pickle issue when using both Python 2 and 3 comes down to when you store data using `PickleType`?:
http://docs.sqlalchemy.org/en/latest/core/type_basics.html#sqlalchemy.types.PickleType

As far as I can see, Stalker currently only uses PickleType for the following:

* Working hours for a project: `mixins.WorkingHoursMixin`
* `Studios.last_schedule_message`

I don't use this, which is perhaps why I haven't stumbled upon any issues when using both Python 2 and 3 to read/write to/from the same db.

Perhaps, in case this is an issue, we could switch out PickleType for something else?

**Comment by jasperges** [comment]
@eoyilmaz To be honest I am not using Stalker actively. I know of it's existence for quite some time now, but didn't really need or understand it. Lately I've taken an interest in it and I hope to use it in production sometime in the future. I followed the tutorial and was fiddling around with it.
Thanks for this awesome project. It seems really nice, with clean code and well thought out. 
@fredrikaverpil Thank you for digging into it a bit further. I think we should indeed create a new issue. Sorry for 'hijacking' yours... :)
I created a new issue: https://github.com/eoyilmaz/stalker/issues/44

**Comment by fredrikaverpil** [comment]
@eoyilmaz do you think you could create a new PyPi release with this fixed?

I'm looking to publish some Python 3 tools in our pipeline in a few weeks and will also need to address this at the same time.

**Comment by eoyilmaz** [comment]
Yes sure, give me a couple of hours, I'll be releasing v0.2.18 with a
couple of changes which are going to break backward compatibility (in
Datetime related fields).

**Comment by fredrikaverpil** [comment]
Awesome! :)

**Comment by eoyilmaz** [comment]
I'm still working on the code, unfortunately it is taking time more than usual. Will try to finish it asap.

**Comment by fredrikaverpil** [comment]
Please take your time, there's no hurry on my behalf. I have a couple of weeks until I need to deploy my new code. 

Let me know if I can help.

**Comment by eoyilmaz** [comment]
Ok it's done! I've upload the v0.2.18 to PyPI :)

Also updating the documentation at: https://www.pythonhosted.org/stalker/index.html

**Comment by fredrikaverpil** [comment]
Wonderful, I'm downloading it now 👍
