### ISSUE TITLE
Automatically attempt to reconnect to db?

### ISSUE THREAD

**Issue by fredrikaverpil** [eoyilmaz/stalker#54]
Is it possible to configure stalker in such a way that it will attempt to reconnect to the db if the connection was for some reason lost?

```
 File "C:\Users\iruser\skalman\condaenvs\skalman_py27\Lib\site-packages\stalker\models\task.py", line 1200, in __eq__
    and self.project == other.project and self.parent == other.parent \
  File "C:\Users\iruser\skalman\condaenvs\skalman_py27\Lib\site-packages\sqlalchemy\orm\attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "C:\Users\iruser\skalman\condaenvs\skalman_py27\Lib\site-packages\sqlalchemy\orm\attributes.py", line 584, in get
    value = self.callable_(state, passive)
  File "C:\Users\iruser\skalman\condaenvs\skalman_py27\Lib\site-packages\sqlalchemy\orm\strategies.py", line 530, in _load_for_state
    (orm_util.state_str(state), self.key)
DetachedInstanceError: Parent instance <Task at 0x24aefc39d68> is not bound to a Session; lazy load operation of attribute 'parent' cannot proceed
```

**Comment by fredrikaverpil** [comment]
Regarding the error snippet I posted above. I'm not sure if the db connection was actually lost or if there's something else going on.

For some reason, we get this `DetachedInstanceError` quite often with Stalker (we're using v0.2.18). Do you have any idea what could be the root cause of this?

This simple code can trigger the above posted snippet:

```python
my_tasks = []
version = Version.query.filter_by(id=version_id).first()
task = version.task

if task not in my_tasks:
    my_tasks = [task]

Traceback:
...
...
...
if task not in my_tasks:
  File "C:\Users\iruser\skalman\condaenvs\skalman_py27\Lib\site-packages\stalker\models\task.py", line 1200, in __eq__
    and self.project == other.project and self.parent == other.parent \
  File "C:\Users\iruser\skalman\condaenvs\skalman_py27\Lib\site-packages\sqlalchemy\orm\attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "C:\Users\iruser\skalman\condaenvs\skalman_py27\Lib\site-packages\sqlalchemy\orm\attributes.py", line 584, in get
    value = self.callable_(state, passive)
  File "C:\Users\iruser\skalman\condaenvs\skalman_py27\Lib\site-packages\sqlalchemy\orm\strategies.py", line 530, in _load_for_state
    (orm_util.state_str(state), self.key)
DetachedInstanceError: Parent instance <Task at 0x1dc50faae48> is not bound to a Session; lazy load operation of attribute 'parent' cannot proceed
```

**Comment by eoyilmaz** [comment]
It is related with the state of the instance. When you commit all of the Python references to the data is set to a state called ``DetachedInstance`` by SQLAlchemy. There is a switch in SQLAlchemy that prevents detaching the instances after commit. But I don't recommend using it.

What I do after a commit is to query the instances again if I plan to do more stuff after ``DBSession.commit()`` at the same scope.

**Comment by fredrikaverpil** [comment]
Do you mean that, after a commit, any variables that I have containing Stalker SOM objects needs to be re-queried?

For example, in our production tool, I have a variable called `current_version` which holds the Stalker SOM `Version` object being worked on. This must be re-queried to avoid such `DetachedInstanceError` errors?

**Comment by eoyilmaz** [comment]
Exactly

**Comment by fredrikaverpil** [comment]
Ok, thanks. Then I've got quite a lot of code to revise here... 😢 
I'll close this issue.

**Comment by fredrikaverpil** [comment]
I have a question regarding the state of an instance... if I have an object assigned to a variable, like so:

```python
>>> print(my_obj)
<Fredrik ('fredrik') (User)>
```

Is there any way I can just re-query this object by passing it into some function?
Or would I have to e.g. fetch its `my_obj.id` and then execute `User.query.filter_by(id=my_obj.id).first()`?

I'm looking for something like `db.DBSession.update(my_obj)`.

**Comment by fredrikaverpil** [comment]
Just coming back to add a note:

I'm now rolling through all variables which hold stalker objects after a db commit. I check whether they have become detached or not and re-query them if necessary.

This can be done like so:

```python
from sqlalchemy import inspect


UPDATED_STALKER_OBJ = None  # Used by requery_stalker_object function

def requery_stalker_object(obj):
    """Returns a re-queried Stalker object"""
    class_name = obj.__class__.__name__
    exec('from stalker import ' + class_name + '; ' +
         'global UPDATED_STALKER_OBJ; ' +
         'UPDATED_STALKER_OBJ = ' + class_name + '.query.filter_by(id=' + str(obj.id) + ').first()')
    return UPDATED_STALKER_OBJ

state = inspect(stalker_obj)
if state.detached:
    requery_stalker_object(obj)

```

If anyone comes up with a more elegant solution, I'm all ears. 😄
