### ISSUE TITLE
date_updated attribute off by one hour (we are UTC+1)

### ISSUE THREAD

**Issue by fredrikaverpil** [eoyilmaz/stalker#55]
Right now, it seems the `SimpleEntity.date_updated` attribute is using UTC (`pytz.utc`) and in our case this means all timestamps are off by one hour since we are UTC+1 (Stockholm, Sweden).

If I were to tell Stalker that we are UTC+1, what would be the best approach?

**Comment by jasperges** [comment]
As I understand it, it's common practice to store `datetime` objects in UTC time in a database. So everybody is on the same page and there is no confusion to what time it is. To show the times correctly for your (users) time zone, you have to do the conversion on the client side.

For how to do that you can have a look [here](https://stackoverflow.com/questions/4563272/convert-a-python-utc-datetime-to-a-local-datetime-using-only-python-standard-lib).

**Comment by eoyilmaz** [comment]
Jasperges is right. Stalker stores the datetime info as UTC. But the latest version supports only non-naive DateTime objects which is a DateTime object with TimeZone information.

So you should use libraries like TZLocal to generate a DateTime object with your local time zone info:

```python
import datetime
import tzlocal

tz = tzlocal.get_localzone()
now = datetime.datetime.now(tzinfo=tz)
```

I'm not on my computer so the code may not work. But the idea behind is like that, everytime you need a datetime instance you generate it normally and inject the time zone information like that. So the database nows how to convert it to UTC. I will update the code when I return back to my computer if it is wrong.

**Comment by fredrikaverpil** [comment]
Ah, thanks for clearing this up @jasperges and @eoyilmaz !

Okay, so this is what I should be doing (using a `Version.date_updated` object and the and `Europe/Stockholm` timezone as example:

```python
import pytz

def utc_to_local(utc_dt):
    local_tz = pytz.timezone('Europe/Stockholm')  # hardcoded
    local_dt = utc_dt.replace(tzinfo=pytz.utc).astimezone(local_tz)
    return local_tz.normalize(local_dt)

local_date_updated = utc_to_local(version.date_updated)
```

I can use `tzlocal` to get the local timezone in case I don't want to hardcode it:

```python
import tzlocal

local_tz = tzlocal.get_localzone()
```

I'll probably move forward using the hardcoded timezone value, just so we can skip the `tzlocal` dependency. Hm, a bit odd that you cannot get the local timezone using `pytz`.

@eoyilmaz I couldn't get your code to work. This worked though:

```python
import datetime
import pytz

now = datetime.datetime.now(pytc.utc)
```

I've read about timezones being a frequent/common problem but never had to solve this personally before. This approach is nice, I like it!

This answers my question and we can close this issue. Thanks so much for the help.

**Comment by eoyilmaz** [comment]
I'm closing the issue but what you're doing with:

```python
now = datetime.datetime.now(pytc.utc)
```

is wrong. It will generate a datetime object that has your local time values (hour, minute, seconds etc.) but the timezone information will tell this is a UTC date.

You'll store the wrong date in your database. But because, I believe, you're also treating this UTC date as a date value in your local time zone by disregarding the timezone info when you retrieve it back from database, you may not see any problems. But this is a time bomb which will blast when you're local timezone changes for daylight saving or you use the same database let say for a web application where you do not have control over the timezone information (which always uses the local timezone).

I recommend using the ``tzlocal`` approach and generating proper datetime objects with your current timezone info.

**Comment by fredrikaverpil** [comment]
> ... but what you're doing with:
> `now = datetime.datetime.now(pytc.utc)`
> is wrong.

Hm. I'm just storing dates like that because that's what I thought @jasperges [was recommending here](https://github.com/eoyilmaz/stalker/issues/55#issuecomment-346756416) and you seem to do this too:
https://github.com/eoyilmaz/stalker/blob/master/stalker/models/entity.py#L195

When I fetch e.g. `Version.updated_by`, the date is UTC-aware but it's not in UTC+1. Since I didn't register this date (Stalker did that automatically upon editing the `Version`), I need to convert it into my local timezone or the date will appear wrong.

Whenever I wish to manually store a date in Stalker, I would prefer to treat it the same way as dates added by Stalker; meaning I'll always have to do apply a timezone to the date when fetched from the database and before presenting it to the user.

Am I not doing this right?

**Comment by eoyilmaz** [comment]
Opps, just ignore my last comment :)

What you're doing is absolutely the correct way of doing it... I've just mixed things up in my head. Not developing for Stalker for a while and apparently I forgot a couple of concepts about Timezones, my bad!

Cheers,

**Comment by fredrikaverpil** [comment]
Phew! 👍
