### ISSUE TITLE
Postgres pubsub for near-realtime updates

### ISSUE THREAD

**Issue by fredrikaverpil** [eoyilmaz/stalker#58]
So I've built this PySide/PyQt based production management UI which runs on top of Stalker and which we have running in Maya, Nuke and as standalone app. The UI runs on each client and needs to be "refreshed" in order to show changes performed by a different client. During certain events, the UI force-refreshes itself to keep it as up to date as possible with the database. An example of this is that I list all versions of a task, but this list doesn't automatically get updated unless the user e.g. updates a version, which is when I perform a query to show anything else that might be new in this list of versions.

The UI feels clunky because of this and is performing unnecessary queries against the database even though there may not be any changes in the database. Therefore I'm interested in looking into how I could use some sort of pubsub mechanism which would listen/notify of database changes for the current project and the UI's models would take appropriate actions based on the queue in the pubsub chat.

Postgres has [built-in support for pubsub](https://www.postgresql.org/docs/9.6/static/sql-notify.html), which could be utilized for this particular thing. I believe it doesn't scale well if you have hundreds of clients (need to look into that) but since Stalker already has Postgres as a dependency, I thought the pubsub of Postgres might be worth looking into first (rather than going with a third-party pubsub solution such as [Celery](http://www.celeryproject.org/) or [RabbitMQ](https://www.rabbitmq.com/)).

@eoyilmaz would you be interested to see Postgres pubsub functionality built into Stalker, or do you feel this will be out of scope for the project?
When running Stalker underneath PySide/PyQt, this feature would really take Stalker to the next level in my opinion.

I still haven't given this enough thought, but this is what I'm thinking initially that I would like to do:
* One channel `#stalker` for notifications on global events which are not tied to a specific project. For example whenever a User, Status or Tag object is updated which is not necessarily tied to the project being browsed.
* One channel per project `#[Project.code]` for notifications on creation/updating/deleting of primarily `Project`, `Task`, `Version` objects (but perhaps best way to implement this is to do it once in the `SimpleEntity` SOM?). I read somewhere that payloads are limited to 8000 bytes, so the notifications would be very simple, I'm thinking something like `#proj1: UPDATE Version.id=20` to notify that the `Version` object with `id=20` was updated.
* Ability to open up custom channels for which you can perform custom `NOTIFY`/`LISTEN`. For example, I could use this to notify of a newer version of my UI tool. But also, you may wish to monitor e.g. all changes made to all Client objects, for some custom reason, regardless of which project you are browsing. In fact, I wish to do exactly this.
* New Stalker submodule handling connecting and disconnecting to channels as well as notifying and listening to a particular channel. This would include making it easy to disconnect from a channel e.g. when the UI has been unresponsive for longer periods of time, or when changing from one project to another (using a frontend such as our UI).
* I'm thinking that any pubsub channel must be explicitly created before any SOM starts notifying into it. There are many scenarios when pubsub functionality is not wanted (when running Stalker on a single client for example). But once the channel exists, the SOM will detect this and notify into it, like described previously.
* Ability to add custom callback functions based different `LISTEN` events, so that e.g. our UI can update its model data based on the pubsub queue.

Also:
* It would be interesting to explore the possibility to run the pubsub on a separate thread, as well as performing queries on a separate thread to avoid e.g. an UI to freeze during a query.

My hopes are that having Stalker underneath a Model-View based PySide UI using pubsub will make the UI feel like it's streaming Stalker data in near real-time, removing the feel of "disconnect" with the surrounding world, alleviating the need for "manual refreshes/querying". Instead, I can make our UI query the objects only when they are being updated, and ideally without a UI freeze.

Here are some related code examples which I'll be looking at:
* https://pypi.python.org/pypi/pgpubsub/0.0.4
* https://gist.github.com/quiver/4240546

Please let me know what your thoughts are about this are.

**Comment by eoyilmaz** [comment]
Sounds very interesting. Let me learn more about it before deciding how to implement it.

**Comment by fredrikaverpil** [comment]
Sure, no problem.

I'm guessing a web-based UI would benefit from this as well.

**Comment by fredrikaverpil** [comment]
I just added some different scenarios and examples in my original post.

Maybe there should just be one single channel which all clients listen to. Then we'd have to design the `NOTIFY` events in such a way that they can be easily filtered.

In short, these are the different scenarios I can foresee that I need:
* Catch all changes related to the current project
* Catch changes related to all SOMs which I've explicitly selected, for example: `Client`, `User`, `Status`.
* Catch changes related to custom events

**Comment by fredrikaverpil** [comment]
Have you had any time to give this any thought?

**Comment by eoyilmaz** [comment]
Not really, sorry. I've been not coding for stalker for a while, and I want to return back to it.

This one and being able to store history for every change done on an entity are my priority features to implement.

**Comment by fredrikaverpil** [comment]
Ok! 😃

**Comment by eoyilmaz** [comment]
hey fredrik I'm back. Just catching up with the SQLAlchemy releases that I've missed and then I want to look at your feature request 👍

**Comment by eoyilmaz** [comment]
Hey Fredrik.

I started to play with the NOTIFY/LISTEN workflow of Postgresql. But I can't make it work from SQLAlchemy.

As far as I know there is a ``notifies`` list in the ``connection`` object of the session. But I can't make it catch the notifications from anywhere

```python
from stalker import db
from stalker.db.session import DBSession
db.setup()
conn = DBSession.connection()
conn.execute("LISTEN test1;")

while True:
    if conn.connection.notifies:
        print(conn.connection.notifies.pop())
```

Update1: While I was testing the code above, all of the notifications from my previous trials have popped up :) so the code is working. Running an SQL query like "NOTIFY test1, 'some data'" will make the loop to pop the data.

Update 2: Now it is down again :(, I don't clearly understand why it is working and then not working. Will play with it.

**Comment by fredrikaverpil** [comment]
Hm. I really haven't researched this at all but I remember seeing this gist not long ago, where the author adds an "[autocommit](http://docs.sqlalchemy.org/en/latest/core/connections.html#understanding-autocommit)" to the execution: https://gist.github.com/dtheodor/3862093af36a1aeb8104

If you add that, does that change anything?
