### ISSUE TITLE
Delete a project with tasks and versions

### ISSUE THREAD

**Issue by fredrikaverpil** [eoyilmaz/stalker#60]
How should I go about deleting a project from the db with all its tasks and all their versions?

It would've been nice to cascade the `Project` delete, but I don't want `User` objects, `Status` objects etc to get deleted which are associated with the project and the versions etc.

I was thinking I could achieve what I want to do in three steps:

1. Delete all `Version` instances which are attached to a `Task` instance in `Project.tasks`
2. Delete all `Task` instances in `Project.tasks`
3. Delete the `Project` instance itself

@eoyilmaz would you recommend some other approach?

**Comment by eoyilmaz** [comment]
Delete operations on a Project instance should already be cascaded to
Tasks, Versions, References etc. Without deleting the User instances. Have
you tried deleting a Project instance.

Erkan Özgür Yılmaz
VFX Supervisor & Photographer
www.youtube.com/erkanozguryilmaz

**Comment by fredrikaverpil** [comment]
Ah. That's awesome. I didn't know exactly what would be included in any cascading.

I just deleted a `Project` instance successfully here.

On the same topic, what if I were to delete a `Repository` instance?
Would it cascade and delete any other instances?

I miss some kind of chart in the docs describing what is deleted and what is kept when deleting. Or perhaps some kind of feedback on the actual `DBSession.delete()`, so that I can see exactly what is about to get deleted (when I commit).

**Comment by eoyilmaz** [comment]
I can update the docs about what is going to be deleted when a specific type of entity is deleted 👍

**Comment by fredrikaverpil** [comment]
Super! Thanks :)

**Comment by eoyilmaz** [comment]
Fixed on 296406e695969a81826ce4bdf14bbd91816b2a2e
