### ISSUE TITLE
Please, recreate the WorkingHours for all Studio instances!

### ISSUE THREAD

**Issue by fredrikaverpil** [eoyilmaz/stalker#65]
Hi,

I am preparing to update from 0.2.18 to 0.2.22. After the `alembic upgrade head`, I get this on a copy of our production database:

```
$ alembic upgrade head
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 31b1e22b455e -> 1181305d3001, Added client_id column to Goods table
INFO  [alembic.runtime.migration] Running upgrade 1181305d3001 -> ed0167fff399, Added WorkingHours table
Warning! Can not keep WorkingHours data of Studios.
Please, recreate the WorkingHours for all Studio instances!
```

@eoyilmaz how do I go about recreating the WorkingHours?

**Comment by fredrikaverpil** [comment]
Oh, wait, I may have realized what this meant. It just means that the old values (if any) were not kept in the db after the upgrade?

We don't use this feature, so I don't really have to do anything. Right?

**Comment by eoyilmaz** [comment]
Hey Fredrik,

Nice to see you around :)
Yes don't worry about that warning if you don't use the WorkingHours 👍
