### ISSUE TITLE
Will Stalker run fine on postgres v11.5?

### ISSUE THREAD

**Issue by fredrikaverpil** [eoyilmaz/stalker#68]
We have been running Stalker on postgres 9.3 since the start. We are now looking to upgrade to the latest 11.5.

@eoyilmaz do you think this is okay or would you recommend not doing this?

**Comment by fredrikaverpil** [comment]
We've been running on 11.5 for a couple of days without issues. Closing...

**Comment by eoyilmaz** [comment]
That's cool 👍

**Comment by eoyilmaz** [comment]
Hey @fredrikaverpil how are you, it's been a while since we got in touch. I'm doing a lot of updates to Stalker and I was wondering if you are still using Stalker in your studio?

**Comment by fredrikaverpil** [comment]
Hey, long time @eoyilmaz 😊
All is good, but I'm not using Stalker personally. I think it's still in use where I implemented a projects mgmt UI.

@stellanhaglund @henriknorin do you know if Skalman is still in use? 🤓
